### ISSUE TITLE
JAFDTC update procedure

### ISSUE THREAD

**Issue by MadogPL** [51st-Vfw/JAFDTC#7]
![image](https://github.com/51st-Vfw/JAFDTC/assets/35303098/9c2e8739-1d81-4ff9-8fed-5b05c906c55c)

I've noticed that it claims that it downloads into download folder, but there is nothing there. There was a previous installation file (but with (1) in filename), but even if I delete all things - it claims there is installation file somewhere. I couldn't find it. Neither did the PC :P 

I do wonder is it connected with the fact that I have my "downloads" location not on C:

![image](https://github.com/51st-Vfw/JAFDTC/assets/35303098/398d6762-fbb5-49d8-856a-73a2f0fa4fdd)

**Comment by ilominar** [comment]
The file with "(1)" in the filename was likely the download. JAFDTC doesn't currently over-write the file, so if it exists, you'll end up with a new copy. Probably go ahead and overwrite with an "Are you sure?" prompt.

JAFDTC should key the path off your profile, so C: versus G: shouldn't matter as long as your profile is on G (which it appears to be from the path above). But I'll check...

**Comment by ilominar** [comment]
Looked at the code and I forgot I how update worked. JAFDTC will prompt to over-write. Next beta will have additional logging on the update path to help figure out what's going wrong. Could be Downloads location, but as I said, shouldn't matter as long as your profile points at G:.

**Comment by MadogPL** [comment]
Ok, I found the confusing part, that's kind of "my setups fault", or windows is not consistant.
![image](https://github.com/51st-Vfw/JAFDTC/assets/35303098/041f346c-6a15-43ea-9a6c-637b7cc3f47d)

**Comment by ilominar** [comment]
UI on download now shows the download path it uses (available next beta). Going to close this...
